### ISSUE TITLE
Load token from file

### ISSUE THREAD

**Issue by nydragon** [orhun/rustypaste-cli#170]
Hey, I found myself to want to pass the token to rpaste through a file, much like I already did for the server (https://github.com/orhun/rustypaste/issues/338).

Previously I was just running `rpaste --auth "$(cat path)"`, but wanted it to be handled directly by rpaste. I've added 2 new fields to the config on my fork (https://github.com/nydragon/rustypaste-cli/commit/a6c64bafae620a0b9aff054e4442e1248fa6ccb7): 

```toml
[server]
address = "https://paste.example.com"
#auth_token = ""
#auth_token_file = "~/example/auth-token"
#delete_token = ""
#delete_token_file = "~/example/delete-token"
```

Would you be interested in my upstreaming it ?
